### ISSUE TITLE
 No module named 'gym_kilobots'

### ISSUE THREAD

**Issue by xinyu-site** [gregorgebhardt/gym-kilobots#1]
hi, I installed the package, but i cant import it.
'No module named 'gym_kilobots''

I run "python setup.py install" in the anaconda prompt and i get the result ‘Finished processing dependencies for gym-kilobots==0.0.1’.

Could you please tell me how to install the gym_kilobots?

**Comment by gregorgebhardt** [comment]
Hi,
thanks for trying out the kilobots-gym and thanks for filing the issue :) There was a `packages` argument missing in the setup. I fixed the bug, please check out the latest state and try again to install the package.

**Comment by xinyu-site** [comment]
Hi，
I tryed again to install the package.But some thing wrong when i run the 'test.py'.

Reloaded modules: __mp_main__
Traceback (most recent call last):

  File "<ipython-input-3-4b430d30b954>", line 1, in <module>
    runfile('C:/Users/yx/Anaconda3/pkgs/gym-kilobots-master/gym_kilobots/test.py', wdir='C:/Users/yx/Anaconda3/pkgs/gym-kilobots-master/gym_kilobots')

  File "C:\Users\yx\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\yx\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/yx/Anaconda3/pkgs/gym-kilobots-master/gym_kilobots/test.py", line 9, in <module>
    env = gym.make('Kilobots-QuadAssembly-v0')

  File "C:\Users\yx\Anaconda3\lib\site-packages\gym\envs\registration.py", line 156, in make
    return registry.make(id, **kwargs)

  File "C:\Users\yx\Anaconda3\lib\site-packages\gym\envs\registration.py", line 100, in make
    spec = self.spec(path)

  File "C:\Users\yx\Anaconda3\lib\site-packages\gym\envs\registration.py", line 142, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))

UnregisteredEnv: No registered env with id: Kilobots-QuadAssembly-v0

**Comment by gregorgebhardt** [comment]
Yeah, the test.py script is very outdated. I should remove it at some point. To test the gym, you need to implement a subclass of KilobotsEnv or use the YamlKilobotsEnv. You can find examples of how I have used the Kilobots Gym [here](https://github.com/gregorgebhardt/kb_learning).

Here is an example for a yaml configuration:
```
env_config:
  !EvalEnv
  width: 1.
  height: 1.
  resolution: 600

  objects:
    - !ObjectConf
      idx: 0
      shape: square
      width: .1
      height: .1
      init: random

  kilobots: !KilobotsConf
    num: 10
    mean: random
    std: .03
```

Note that the Kilobots Gym is not under active development and not maintained at the moment. So to get it running for your purposes you might have to dive into the code to understand how things work.

**Comment by margalordyzd** [comment]
Hi @gregorgebhardt , I had the same issue as @xjtueryx but its no completely clear to me how to run your code, i took a look at your other examples of how you use the kilobots but i still couldn't figure out how to run the kilobots. Coul you provide a simple working example or guide me towards which commands do i need to run for the code to work. 

Thank you for your time
